/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MenuCategory = { 'mainCourse' : null } |
  { 'dessert' : null } |
  { 'appetizer' : null } |
  { 'beverage' : null };
export interface MenuItem {
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : MenuCategory,
  'price' : bigint,
}
export interface Reservation {
  'status' : ReservationStatus,
  'date' : Time,
  'name' : string,
  'specialRequests' : string,
  'createdAt' : Time,
  'time' : string,
  'phone' : string,
  'guests' : bigint,
}
export type ReservationStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type Time = bigint;
export interface UpdateMenuItemData {
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : MenuCategory,
  'price' : bigint,
}
export interface _SERVICE {
  'addMenuItem' : ActorMethod<[MenuItem], bigint>,
  'createReservation' : ActorMethod<[Reservation], bigint>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getReservationsByTimeRange' : ActorMethod<[Time, Time], Array<Reservation>>,
  'prepopulate' : ActorMethod<[], undefined>,
  'updateMenuItem' : ActorMethod<[bigint, UpdateMenuItemData], undefined>,
  'updateReservationStatus' : ActorMethod<
    [bigint, ReservationStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];