/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuCategory = IDL.Variant({
  'mainCourse' : IDL.Null,
  'dessert' : IDL.Null,
  'appetizer' : IDL.Null,
  'beverage' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : MenuCategory,
  'price' : IDL.Nat,
});
export const ReservationStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Reservation = IDL.Record({
  'status' : ReservationStatus,
  'date' : Time,
  'name' : IDL.Text,
  'specialRequests' : IDL.Text,
  'createdAt' : Time,
  'time' : IDL.Text,
  'phone' : IDL.Text,
  'guests' : IDL.Nat,
});
export const UpdateMenuItemData = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : MenuCategory,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
  'createReservation' : IDL.Func([Reservation], [IDL.Nat], []),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getReservationsByTimeRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'prepopulate' : IDL.Func([], [], []),
  'updateMenuItem' : IDL.Func([IDL.Nat, UpdateMenuItemData], [], []),
  'updateReservationStatus' : IDL.Func([IDL.Nat, ReservationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuCategory = IDL.Variant({
    'mainCourse' : IDL.Null,
    'dessert' : IDL.Null,
    'appetizer' : IDL.Null,
    'beverage' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : MenuCategory,
    'price' : IDL.Nat,
  });
  const ReservationStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Reservation = IDL.Record({
    'status' : ReservationStatus,
    'date' : Time,
    'name' : IDL.Text,
    'specialRequests' : IDL.Text,
    'createdAt' : Time,
    'time' : IDL.Text,
    'phone' : IDL.Text,
    'guests' : IDL.Nat,
  });
  const UpdateMenuItemData = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : MenuCategory,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func([MenuItem], [IDL.Nat], []),
    'createReservation' : IDL.Func([Reservation], [IDL.Nat], []),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getReservationsByTimeRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'prepopulate' : IDL.Func([], [], []),
    'updateMenuItem' : IDL.Func([IDL.Nat, UpdateMenuItemData], [], []),
    'updateReservationStatus' : IDL.Func([IDL.Nat, ReservationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };