/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateMenuItemData {
    name: string;
    description: string;
    imageUrl: string;
    category: MenuCategory;
    price: bigint;
}
export interface Reservation {
    status: ReservationStatus;
    date: Time;
    name: string;
    specialRequests: string;
    createdAt: Time;
    time: string;
    phone: string;
    guests: bigint;
}
export interface MenuItem {
    name: string;
    description: string;
    imageUrl: string;
    category: MenuCategory;
    price: bigint;
}
export type Time = bigint;
export enum MenuCategory {
    mainCourse = "mainCourse",
    dessert = "dessert",
    appetizer = "appetizer",
    beverage = "beverage"
}
export enum ReservationStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export interface backendInterface {
    addMenuItem(item: MenuItem): Promise<bigint>;
    createReservation(reservation: Reservation): Promise<bigint>;
    getAllReservations(): Promise<Array<Reservation>>;
    getMenu(): Promise<Array<MenuItem>>;
    getReservationsByTimeRange(start: Time, end: Time): Promise<Array<Reservation>>;
    prepopulate(): Promise<void>;
    updateMenuItem(id: bigint, update: UpdateMenuItemData): Promise<void>;
    updateReservationStatus(id: bigint, status: ReservationStatus): Promise<void>;
}
import type { MenuCategory as _MenuCategory, MenuItem as _MenuItem, Reservation as _Reservation, ReservationStatus as _ReservationStatus, Time as _Time, UpdateMenuItemData as _UpdateMenuItemData } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMenuItem(arg0: MenuItem): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(to_candid_MenuItem_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(to_candid_MenuItem_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createReservation(arg0: Reservation): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReservation(to_candid_Reservation_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReservation(to_candid_Reservation_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllReservations(): Promise<Array<Reservation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReservations();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReservations();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenu(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenu();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenu();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReservationsByTimeRange(arg0: Time, arg1: Time): Promise<Array<Reservation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReservationsByTimeRange(arg0, arg1);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReservationsByTimeRange(arg0, arg1);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async prepopulate(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.prepopulate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.prepopulate();
            return result;
        }
    }
    async updateMenuItem(arg0: bigint, arg1: UpdateMenuItemData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, to_candid_UpdateMenuItemData_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, to_candid_UpdateMenuItemData_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateReservationStatus(arg0: bigint, arg1: ReservationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReservationStatus(arg0, to_candid_ReservationStatus_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReservationStatus(arg0, to_candid_ReservationStatus_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_MenuCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuCategory): MenuCategory {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ReservationStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReservationStatus): ReservationStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Reservation_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reservation): Reservation {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ReservationStatus;
    date: _Time;
    name: string;
    specialRequests: string;
    createdAt: _Time;
    time: string;
    phone: string;
    guests: bigint;
}): {
    status: ReservationStatus;
    date: Time;
    name: string;
    specialRequests: string;
    createdAt: Time;
    time: string;
    phone: string;
    guests: bigint;
} {
    return {
        status: from_candid_ReservationStatus_n12(_uploadFile, _downloadFile, value.status),
        date: value.date,
        name: value.name,
        specialRequests: value.specialRequests,
        createdAt: value.createdAt,
        time: value.time,
        phone: value.phone,
        guests: value.guests
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    imageUrl: string;
    category: _MenuCategory;
    price: bigint;
}): {
    name: string;
    description: string;
    imageUrl: string;
    category: MenuCategory;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_MenuCategory_n17(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): ReservationStatus {
    return "cancelled" in value ? ReservationStatus.cancelled : "pending" in value ? ReservationStatus.pending : "confirmed" in value ? ReservationStatus.confirmed : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mainCourse: null;
} | {
    dessert: null;
} | {
    appetizer: null;
} | {
    beverage: null;
}): MenuCategory {
    return "mainCourse" in value ? MenuCategory.mainCourse : "dessert" in value ? MenuCategory.dessert : "appetizer" in value ? MenuCategory.appetizer : "beverage" in value ? MenuCategory.beverage : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reservation>): Array<Reservation> {
    return value.map((x)=>from_candid_Reservation_n10(_uploadFile, _downloadFile, x));
}
function to_candid_MenuCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): _MenuCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MenuItem_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): _MenuItem {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ReservationStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReservationStatus): _ReservationStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Reservation_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Reservation): _Reservation {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateMenuItemData_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateMenuItemData): _UpdateMenuItemData {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    imageUrl: string;
    category: MenuCategory;
    price: bigint;
}): {
    name: string;
    description: string;
    imageUrl: string;
    category: _MenuCategory;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        category: to_candid_MenuCategory_n3(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ReservationStatus;
    date: Time;
    name: string;
    specialRequests: string;
    createdAt: Time;
    time: string;
    phone: string;
    guests: bigint;
}): {
    status: _ReservationStatus;
    date: _Time;
    name: string;
    specialRequests: string;
    createdAt: _Time;
    time: string;
    phone: string;
    guests: bigint;
} {
    return {
        status: to_candid_ReservationStatus_n7(_uploadFile, _downloadFile, value.status),
        date: value.date,
        name: value.name,
        specialRequests: value.specialRequests,
        createdAt: value.createdAt,
        time: value.time,
        phone: value.phone,
        guests: value.guests
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): {
    mainCourse: null;
} | {
    dessert: null;
} | {
    appetizer: null;
} | {
    beverage: null;
} {
    return value == MenuCategory.mainCourse ? {
        mainCourse: null
    } : value == MenuCategory.dessert ? {
        dessert: null
    } : value == MenuCategory.appetizer ? {
        appetizer: null
    } : value == MenuCategory.beverage ? {
        beverage: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReservationStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == ReservationStatus.cancelled ? {
        cancelled: null
    } : value == ReservationStatus.pending ? {
        pending: null
    } : value == ReservationStatus.confirmed ? {
        confirmed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
